"""IRIS v8 Project Generator — Scaffold Next.js, FastAPI, Flask projects"""
import os
import json
import shutil
import subprocess
from datetime import datetime
from typing import Dict, List, Optional
from config import config

class ProjectGenerator:
    """
    Generate complete project scaffolding:
    - Next.js (React + TypeScript + Tailwind)
    - FastAPI (Python API)
    - Flask (Python web)
    """

    TEMPLATES = {
        "nextjs": {
            "description": "Next.js 14 with TypeScript, Tailwind, shadcn/ui",
            "files": {
                "package.json": '{\n  "name": "{{name}}",\n  "version": "0.1.0",\n  "private": true,\n  "scripts": {\n    "dev": "next dev",\n    "build": "next build",\n    "start": "next start",\n    "lint": "next lint"\n  },\n  "dependencies": {\n    "next": "^14.0.0",\n    "react": "^18.2.0",\n    "react-dom": "^18.2.0",\n    "tailwindcss": "^3.3.0"\n  },\n  "devDependencies": {\n    "typescript": "^5.2.0",\n    "@types/node": "^20.0.0",\n    "@types/react": "^18.2.0",\n    "autoprefixer": "^10.4.16",\n    "postcss": "^8.4.31"\n  }\n}',
                "tsconfig.json": '{\n  "compilerOptions": {\n    "lib": ["dom", "dom.iterable", "esnext"],\n    "allowJs": true,\n    "skipLibCheck": true,\n    "strict": true,\n    "noEmit": true,\n    "esModuleInterop": true,\n    "module": "esnext",\n    "moduleResolution": "bundler",\n    "resolveJsonModule": true,\n    "isolatedModules": true,\n    "jsx": "preserve",\n    "incremental": true,\n    "paths": {"@/*": ["./*"]}\n  },\n  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],\n  "exclude": ["node_modules"]\n}',
                "tailwind.config.ts": "import type { Config } from 'tailwindcss'\n\nconst config: Config = {\n  content: [\n    './pages/**/*.{js,ts,jsx,tsx,mdx}',\n    './components/**/*.{js,ts,jsx,tsx,mdx}',\n    './app/**/*.{js,ts,jsx,tsx,mdx}',\n  ],\n  theme: {\n    extend: {\n      colors: {\n        primary: '#4a90d9',\n        secondary: '#1a5276',\n      }\n    }\n  },\n  plugins: []\n}\nexport default config",
                "postcss.config.js": "module.exports = {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {}\n  }\n}",
                "app/globals.css": "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n:root {\n  --foreground-rgb: 0, 0, 0;\n  --background-start-rgb: 214, 219, 220;\n  --background-end-rgb: 255, 255, 255;\n}\n\nbody {\n  color: rgb(var(--foreground-rgb));\n  background: linear-gradient(\n      to bottom,\n      transparent,\n      rgb(var(--background-end-rgb))\n    )\n    rgb(var(--background-start-rgb));\n}",
                "app/layout.tsx": "import type { Metadata } from 'next'\nimport { Inter } from 'next/font/google'\nimport './globals.css'\n\nconst inter = Inter({ subsets: ['latin'] })\n\nexport const metadata: Metadata = {\n  title: '{{name}}',\n  description: 'Generated by IRIS',\n}\n\nexport default function RootLayout({\n  children,\n}: {\n  children: React.ReactNode\n}) {\n  return (\n    <html lang='en'>\n      <body className={inter.className}>{children}</body>\n    </html>\n  )\n}",
                "app/page.tsx": "export default function Home() {\n  return (\n    <main className='flex min-h-screen flex-col items-center justify-between p-24'>\n      <div className='z-10 max-w-5xl w-full items-center justify-between font-mono text-sm'>\n        <h1 className='text-4xl font-bold text-center mb-8'>{{name}}</h1>\n        <p className='text-center text-gray-600'>\n          Built with IRIS — Infinite Reactive Intelligence System\n        </p>\n      </div>\n    </main>\n  )\n}",
                "next.config.js": "/** @type {import('next').NextConfig} */\nconst nextConfig = {}\nmodule.exports = nextConfig",
                ".gitignore": "# Dependencies\n/node_modules\n/.pnp\n.pnp.js\n\n# Testing\n/coverage\n\n# Next.js\n/.next/\n/out/\n\n# Production\n/build\n\n# Misc\n.DS_Store\n*.pem\n\n# Debug\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n\n# Local env files\n.env*.local\n.env",
                "vercel.json": '{\n  "version": 2,\n  "builds": [{\n    "src": "package.json",\n    "use": "@vercel/static-build"\n  }]\n}'
            }
        },
        "fastapi": {
            "description": "FastAPI with SQLAlchemy, Pydantic, JWT auth",
            "files": {
                "requirements.txt": "fastapi==0.104.1\nuvicorn[standard]==0.24.0\nsqlalchemy==2.0.23\npydantic==2.5.0\npydantic-settings==2.1.0\npython-jose[cryptography]==3.3.0\npasslib[bcrypt]==1.7.4\npython-multipart==0.0.6\nalembic==1.12.1\npytest==7.4.3\nhttpx==0.25.2",
                "app/main.py": "from fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\n\napp = FastAPI(\n    title='{{name}}',\n    description='API generated by IRIS',\n    version='0.1.0'\n)\n\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=['*'],\n    allow_credentials=True,\n    allow_methods=['*'],\n    allow_headers=['*'],\n)\n\n@app.get('/')\nasync def root():\n    return {'message': 'Welcome to {{name}}', 'powered_by': 'IRIS'}\n\n@app.get('/health')\nasync def health():\n    return {'status': 'healthy'}",
                "app/__init__.py": "",
                "app/database.py": "from sqlalchemy import create_engine\nfrom sqlalchemy.ext.declarative import declarative_base\nfrom sqlalchemy.orm import sessionmaker\n\nSQLALCHEMY_DATABASE_URL = 'sqlite:///./{{name}}.db'\n\nengine = create_engine(\n    SQLALCHEMY_DATABASE_URL, connect_args={'check_same_thread': False}\n)\nSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)\nBase = declarative_base()\n\ndef get_db():\n    db = SessionLocal()\n    try:\n        yield db\n    finally:\n        db.close()",
                "Dockerfile": "FROM python:3.11-slim\n\nWORKDIR /app\n\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\n\nCOPY . .\n\nCMD ['uvicorn', 'app.main:app', '--host', '0.0.0.0', '--port', '8000']",
                "docker-compose.yml": "version: '3.8'\n\nservices:\n  api:\n    build: .\n    ports:\n      - '8000:8000'\n    volumes:\n      - .:/app\n    environment:\n      - DATABASE_URL=sqlite:///./{{name}}.db\n    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload",
                ".env.example": "DATABASE_URL=sqlite:///./{{name}}.db\nSECRET_KEY=your-secret-key-here\nALGORITHM=HS256\nACCESS_TOKEN_EXPIRE_MINUTES=30",
                ".gitignore": "__pycache__/\n*.py[cod]\n*$py.class\n*.so\n.Python\nenv/\nvenv/\nENV/\n.venv\n*.db\n*.sqlite3\n.env\n.DS_Store"
            }
        },
        "flask": {
            "description": "Flask web app with SQLAlchemy, Jinja2 templates",
            "files": {
                "requirements.txt": "Flask==3.0.0\nFlask-SQLAlchemy==3.1.1\nFlask-Login==0.6.3\nFlask-WTF==1.2.1\nWTForms==3.1.1\nWerkzeug==3.0.1\npython-dotenv==1.0.0\ngunicorn==21.2.0",
                "app.py": "from flask import Flask, render_template, request, redirect, url_for, flash\nfrom flask_sqlalchemy import SQLAlchemy\nfrom datetime import datetime\nimport os\n\napp = Flask(__name__)\napp.config['SECRET_KEY'] = os.getenv('SECRET_KEY', 'dev-secret-key')\napp.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URL', 'sqlite:///{{name}}.db')\napp.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False\n\ndb = SQLAlchemy(app)\n\nclass Item(db.Model):\n    id = db.Column(db.Integer, primary_key=True)\n    title = db.Column(db.String(100), nullable=False)\n    description = db.Column(db.Text)\n    created_at = db.Column(db.DateTime, default=datetime.utcnow)\n\n@app.route('/')\ndef index():\n    items = Item.query.order_by(Item.created_at.desc()).all()\n    return render_template('index.html', items=items)\n\n@app.route('/add', methods=['POST'])\ndef add_item():\n    title = request.form.get('title')\n    description = request.form.get('description')\n    if title:\n        item = Item(title=title, description=description)\n        db.session.add(item)\n        db.session.commit()\n        flash('Item added!', 'success')\n    return redirect(url_for('index'))\n\nif __name__ == '__main__':\n    with app.app_context():\n        db.create_all()\n    app.run(debug=True)",
                "templates/base.html": "<!DOCTYPE html>\n<html>\n<head>\n    <title>{% block title %}{{name}}{% endblock %}</title>\n    <style>\n        body { font-family: sans-serif; background: #f5f5f5; margin: 0; }\n        .header { background: linear-gradient(135deg, #667eea, #764ba2); color: white; padding: 40px; text-align: center; }\n        .container { max-width: 800px; margin: 0 auto; padding: 20px; }\n        .card { background: white; border-radius: 12px; padding: 24px; margin: 20px 0; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }\n        .btn { background: #667eea; color: white; border: none; padding: 12px 24px; border-radius: 8px; cursor: pointer; }\n        input, textarea { width: 100%; padding: 12px; margin: 8px 0; border: 1px solid #ddd; border-radius: 8px; }\n    </style>\n</head>\n<body>\n    <div class='header'>\n        <h1>{{name}}</h1>\n        <p>Built with IRIS</p>\n    </div>\n    <div class='container'>\n        {% block content %}{% endblock %}\n    </div>\n</body>\n</html>",
                "templates/index.html": "{% extends 'base.html' %}\n{% block content %}\n<div class='card'>\n    <h2>Add New Item</h2>\n    <form action='{{ url_for(\"add_item\") }}' method='POST'>\n        <input type='text' name='title' placeholder='Title' required>\n        <textarea name='description' placeholder='Description' rows='3'></textarea>\n        <button type='submit' class='btn'>Add Item</button>\n    </form>\n</div>\n<div class='card'>\n    <h2>Items</h2>\n    {% for item in items %}\n    <div style='padding: 16px; border-bottom: 1px solid #eee;'>\n        <h3>{{ item.title }}</h3>\n        <p>{{ item.description or 'No description' }}</p>\n    </div>\n    {% else %}\n    <p>No items yet.</p>\n    {% endfor %}\n</div>\n{% endblock %}",
                ".env.example": "SECRET_KEY=your-secret-key-here\nDATABASE_URL=sqlite:///{{name}}.db",
                ".gitignore": "__pycache__/\n*.py[cod]\n*$py.class\n*.so\n.Python\nenv/\nvenv/\nENV/\n.venv\n*.db\n*.sqlite3\n.env\n.DS_Store"
            }
        }
    }

    def __init__(self):
        self.projects_dir = os.path.join(config.DATA_DIR, "projects")
        os.makedirs(self.projects_dir, exist_ok=True)

    def generate_project(self, project_name: str, template: str = "nextjs", description: str = "") -> Dict:
        if template not in self.TEMPLATES:
            return {"success": False, "error": f"Unknown template: {template}"}

        template_data = self.TEMPLATES[template]
        project_path = os.path.join(self.projects_dir, project_name)

        if os.path.exists(project_path):
            return {"success": False, "error": f"Project '{project_name}' already exists"}

        os.makedirs(project_path, exist_ok=True)
        files_created = []

        for file_path, content in template_data["files"].items():
            full_path = os.path.join(project_path, file_path)
            os.makedirs(os.path.dirname(full_path), exist_ok=True)
            rendered = content.replace("{{name}}", project_name).replace("{{description}}", description)
            with open(full_path, "w") as f:
                f.write(rendered)
            files_created.append(file_path)

        # README
        readme = f"# {project_name}\n\n{description}\n\nGenerated by IRIS v8\n\n## Template: {template}\n\n{template_data['description']}\n\n## Getting Started\n\n"
        if template == "nextjs":
            readme += "```bash\nnpm install\nnpm run dev\n```\n"
        elif template == "fastapi":
            readme += "```bash\npip install -r requirements.txt\nuvicorn app.main:app --reload\n```\n"
        elif template == "flask":
            readme += "```bash\npip install -r requirements.txt\npython app.py\n```\n"

        with open(os.path.join(project_path, "README.md"), "w") as f:
            f.write(readme)

        return {
            "success": True,
            "project_name": project_name,
            "template": template,
            "path": project_path,
            "files_created": files_created
        }

    def deploy_project(self, project_name: str, repo_name: str = None, deploy_to_vercel: bool = True) -> Dict:
        project_path = os.path.join(self.projects_dir, project_name)
        if not os.path.exists(project_path):
            return {"success": False, "error": f"Project '{project_name}' not found"}

        repo_name = repo_name or project_name
        from core.tool_registry import tool_registry
        repo_result = tool_registry.tools["git_create_repo"](name=repo_name, description=f"Generated by IRIS: {project_name}")
        if not repo_result.success:
            return {"success": False, "error": f"Failed to create repo: {repo_result.error}"}

        subprocess.run(["git", "init"], cwd=project_path, capture_output=True)
        subprocess.run(["git", "add", "."], cwd=project_path, capture_output=True)
        subprocess.run(["git", "commit", "-m", "Initial commit by IRIS"], cwd=project_path, capture_output=True)
        subprocess.run(["git", "branch", "-M", "main"], cwd=project_path, capture_output=True)
        subprocess.run(["git", "remote", "add", "origin", repo_result.data["clone_url"]], cwd=project_path, capture_output=True)
        subprocess.run(["git", "push", "-u", "origin", "main"], cwd=project_path, capture_output=True)

        vercel_url = None
        if deploy_to_vercel:
            vercel_result = tool_registry.tools["vercel_deploy"](project_path=project_path, project_name=repo_name)
            if vercel_result.success:
                vercel_url = vercel_result.data.get("url")

        return {
            "success": True,
            "repo_url": repo_result.data.get("url"),
            "clone_url": repo_result.data.get("clone_url"),
            "vercel_url": vercel_url
        }

    def get_projects(self) -> List[Dict]:
        projects = []
        if os.path.exists(self.projects_dir):
            for name in os.listdir(self.projects_dir):
                path = os.path.join(self.projects_dir, name)
                if os.path.isdir(path):
                    projects.append({
                        "name": name,
                        "path": path,
                        "created": datetime.fromtimestamp(os.path.getctime(path)).isoformat()
                    })
        return projects

    def get_available_templates(self) -> Dict:
        return {k: v["description"] for k, v in self.TEMPLATES.items()}

# Singleton
project_generator = ProjectGenerator()
